// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Dissolve(arg1) {
  return window['go']['app']['ClusterService']['Dissolve'](arg1);
}

export function Group(arg1) {
  return window['go']['app']['ClusterService']['Group'](arg1);
}

export function List() {
  return window['go']['app']['ClusterService']['List']();
}

export function Preflight(arg1) {
  return window['go']['app']['ClusterService']['Preflight'](arg1);
}
