// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function Dissolve(arg1:string):Promise<void>;

export function Group(arg1:app.GroupRequest):Promise<void>;

export function List():Promise<Array<app.ReplicaSetView>>;

export function Preflight(arg1:Array<string>):Promise<app.PreflightReport>;
