// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {metrics} from '../models';
import {logstream} from '../models';

export function Create(arg1:app.CreateInstanceRequest):Promise<app.InstanceView>;

export function Databases(arg1:string):Promise<Array<metrics.DatabaseInfo>>;

export function List():Promise<Array<app.InstanceView>>;

export function Logs(arg1:string):Promise<Array<logstream.Line>>;

export function MetricsHistory(arg1:string):Promise<Array<metrics.Sample>>;

export function MoveDataDir(arg1:string,arg2:string):Promise<void>;

export function ReadConfig(arg1:string):Promise<string>;

export function Remove(arg1:string,arg2:boolean):Promise<void>;

export function Restart(arg1:string):Promise<void>;

export function Start(arg1:string):Promise<void>;

export function Stop(arg1:string):Promise<void>;

export function SuggestPort():Promise<number>;

export function WriteConfig(arg1:string,arg2:string):Promise<void>;
