// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['app']['InstanceService']['Create'](arg1);
}

export function Databases(arg1) {
  return window['go']['app']['InstanceService']['Databases'](arg1);
}

export function List() {
  return window['go']['app']['InstanceService']['List']();
}

export function Logs(arg1) {
  return window['go']['app']['InstanceService']['Logs'](arg1);
}

export function MetricsHistory(arg1) {
  return window['go']['app']['InstanceService']['MetricsHistory'](arg1);
}

export function MoveDataDir(arg1, arg2) {
  return window['go']['app']['InstanceService']['MoveDataDir'](arg1, arg2);
}

export function ReadConfig(arg1) {
  return window['go']['app']['InstanceService']['ReadConfig'](arg1);
}

export function Remove(arg1, arg2) {
  return window['go']['app']['InstanceService']['Remove'](arg1, arg2);
}

export function Restart(arg1) {
  return window['go']['app']['InstanceService']['Restart'](arg1);
}

export function Start(arg1) {
  return window['go']['app']['InstanceService']['Start'](arg1);
}

export function Stop(arg1) {
  return window['go']['app']['InstanceService']['Stop'](arg1);
}

export function SuggestPort() {
  return window['go']['app']['InstanceService']['SuggestPort']();
}

export function WriteConfig(arg1, arg2) {
  return window['go']['app']['InstanceService']['WriteConfig'](arg1, arg2);
}
