// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AvailableBinaries() {
  return window['go']['app']['SystemService']['AvailableBinaries']();
}

export function ChooseDirectory(arg1) {
  return window['go']['app']['SystemService']['ChooseDirectory'](arg1);
}

export function Info() {
  return window['go']['app']['SystemService']['Info']();
}

export function ServiceReadConfig() {
  return window['go']['app']['SystemService']['ServiceReadConfig']();
}

export function ServiceRestart() {
  return window['go']['app']['SystemService']['ServiceRestart']();
}

export function ServiceSetStartType(arg1) {
  return window['go']['app']['SystemService']['ServiceSetStartType'](arg1);
}

export function ServiceStart() {
  return window['go']['app']['SystemService']['ServiceStart']();
}

export function ServiceStop() {
  return window['go']['app']['SystemService']['ServiceStop']();
}

export function ServiceWriteConfig(arg1) {
  return window['go']['app']['SystemService']['ServiceWriteConfig'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['app']['SystemService']['UpdateSettings'](arg1);
}
