// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {mongobin} from '../models';
import {app} from '../models';
import {store} from '../models';

export function AvailableBinaries():Promise<Array<mongobin.Binary>>;

export function ChooseDirectory(arg1:string):Promise<string>;

export function Info():Promise<app.SystemInfo>;

export function ServiceReadConfig():Promise<string>;

export function ServiceRestart():Promise<void>;

export function ServiceSetStartType(arg1:string):Promise<void>;

export function ServiceStart():Promise<void>;

export function ServiceStop():Promise<void>;

export function ServiceWriteConfig(arg1:string):Promise<void>;

export function UpdateSettings(arg1:store.Settings):Promise<store.Settings>;
